In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

**Summary of the dataset**

This dataset acts as a Supply Chain Efficiency Monitor, providing a complete view of how products move from suppliers to customers while tracking time, inventory, and costs. It is structured around three key areas: logistics, which helps identify delays in processing and shipping; inventory, which ensures optimal stock levels and highlights risks like shortages or overstocking; and financials, which evaluate overall profitability by analyzing sales and various costs. Together, these elements make the dataset a powerful diagnostic tool that helps identify inefficiencies, reduce costs, and improve overall business performance.

In [2]:
df = pd.read_csv("C:/Users/acer/OneDrive/Desktop/Supply_chain/Dataset/supply_chain.csv")

df.shape

(500, 20)

**Column Description**

Warehouse ID : The ID of the warehouse 

Location : Warehouse Location 

Current Stock : Present Quantity

Demand_Forecast: Expected future demand

Lead_Time_Days: Time taken to restock items

Shipping_Time_Days: Time taken to deliver orders

Stockout_Risk: Risk of running out of stock

Operational_Cost: Daily/overall operating cost

Supplier_ID: Unique ID of supplier

Product_Category: Type of product

Monthly_Sales: Total sales per month

Order_Processing_Time: Time to process an order

Return_Rate: Percentage of returned products

Customer_Rating: Customer feedback score

Warehouse_Capacity: Maximum storage limit

Storage_Cost: Cost of storing goods

Transportation_Cost: Cost of shipping goods

Backorder_Quantity: Orders not fulfilled due to low stock

Damaged_Goods: Number of damaged items

Employee_count : no. of employees works in a warehouse.

In [3]:
df.head()

,Warehouse_ID,Location,Current_Stock,Demand_Forecast,Lead_Time_Days,Shipping_Time_Days,Stockout_Risk,Operational_Cost,Supplier_ID,Product_Category,Monthly_Sales,Order_Processing_Time,Return_Rate,Customer_Rating,Warehouse_Capacity,Storage_Cost,Transportation_Cost,Backorder_Quantity,Damaged_Goods,Employee_Count
0,WH239,Dallas,3926,484,8,3,7,93895,S693,Groceries,4893,4.766231,6.053952,3.840976,28701,16975,2778,228,26,83
1,WH244,Houston,3032,5122,3,6,25,46847,S880,Electronics,4453,4.304335,3.886996,2.113929,36198,14052,1535,288,16,39
2,WH340,Chicago,4763,4343,5,5,16,64176,S116,Furniture,5956,1.030779,7.335160,4.211437,22784,9863,13435,153,3,49
3,WH428,Atlanta,2219,777,7,6,15,38940,S431,Apparel,5814,2.871244,1.393481,1.751671,13172,15911,14508,143,39,35
4,WH202,Dallas,809,4756,2,7,16,33933,S821,Electronics,2279,4.060930,4.212666,4.231919,39619,19011,1904,296,30,67

In [4]:
df.tail()

,Warehouse_ID,Location,Current_Stock,Demand_Forecast,Lead_Time_Days,Shipping_Time_Days,Stockout_Risk,Operational_Cost,Supplier_ID,Product_Category,Monthly_Sales,Order_Processing_Time,Return_Rate,Customer_Rating,Warehouse_Capacity,Storage_Cost,Transportation_Cost,Backorder_Quantity,Damaged_Goods,Employee_Count
495,WH145,New York,4357,1521,10,5,20,65281,S830,Groceries,5909,3.938249,5.445214,1.829305,47701,1581,5792,119,43,97
496,WH181,Miami,3110,3322,4,7,8,88426,S663,Groceries,4584,3.786971,1.452853,4.916439,48667,4070,9536,47,29,77
497,WH068,Seattle,1636,4170,4,3,6,87751,S961,Apparel,1699,0.683904,8.474156,4.142398,17858,9501,5919,9,38,61
498,WH204,Seattle,1821,536,9,6,23,78229,S966,Electronics,8828,1.298125,7.006858,1.150413,12831,7219,3575,204,24,48
499,WH047,Dallas,2309,3122,7,3,16,84305,S185,Automotive,7267,4.222160,2.153669,2.355345,23096,6377,14269,254,15,6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Warehouse_ID           500 non-null    object
 1   Location               500 non-null    object
 2   Current_Stock          500 non-null    int64
 3   Demand_Forecast        500 non-null    int64
 4   Lead_Time_Days         500 non-null    int64
 5   Shipping_Time_Days     500 non-null    int64
 6   Stockout_Risk          500 non-null    int64
 7   Operational_Cost       500 non-null    int64
 8   Supplier_ID            500 non-null    object
 9   Product_Category       500 non-null    object
 10  Monthly_Sales          500 non-null    int64
 11  Order_Processing_Time  500 non-null    float64
 12  Return_Rate            500 non-null    float64
 13  Customer_Rating        500 non-null    float64
 14  Warehouse_Capacity     500 non-null    int64
 15  Storage_Cost           500 non-null    int64
 16  Transportation_Cost    500 non-null    int64
 17  Backorder_Quantity     500 non-null    int64
 18  Damaged_Goods          500 non-null    int64
 19  Employee_Count         500 non-null    int64
dtypes: float64(3), int64(13), object(4)
memory usage: 78.3+ KB

In [6]:
df['Location'].value_counts(dropna=False)

Location
Miami            56
Atlanta          55
Los Angeles      54
New York         54
San Francisco    52
Dallas           51
Denver           46
Houston          44
Chicago          44
Seattle          44
Name: count, dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

,Current_Stock,Demand_Forecast,Lead_Time_Days,Shipping_Time_Days,Stockout_Risk,Operational_Cost,Monthly_Sales,Order_Processing_Time,Return_Rate,Customer_Rating,Warehouse_Capacity,Storage_Cost,Transportation_Cost,Backorder_Quantity,Damaged_Goods,Employee_Count
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,2722.822000,2957.050000,5.958000,3.948000,14.944000,65886.354000,5335.572000,2.750462,5.229366,3.090865,30032.818000,10263.83400,8001.086000,147.380000,24.684000,52.810000
std,1314.878786,1398.763988,2.630223,1.921635,5.923431,20283.576821,2619.353688,1.262967,2.661448,1.156971,11921.277948,5584.14567,4269.354045,87.880656,14.868298,27.888087
min,519.000000,402.000000,2.000000,1.000000,5.000000,30165.000000,1004.000000,0.505159,0.506755,1.004825,10338.000000,1083.00000,515.000000,0.000000,0.000000,5.000000
25%,1565.250000,1745.750000,4.000000,2.000000,10.000000,48731.750000,2978.000000,1.644623,3.085484,2.073853,19486.750000,5335.75000,4294.500000,71.750000,11.000000,28.000000
50%,2670.000000,3094.000000,6.000000,4.000000,15.000000,65733.500000,5234.000000,2.817771,5.128133,3.148014,29862.500000,10023.00000,7973.000000,141.000000,25.000000,53.000000
75%,3842.750000,4152.500000,8.000000,6.000000,20.000000,82900.250000,7550.750000,3.782273,7.406404,4.137274,40692.250000,15162.00000,11857.000000,224.000000,37.000000,78.000000
max,4998.000000,5200.000000,10.000000,7.000000,25.000000,99965.000000,9931.000000,4.954139,9.992465,4.998258,49979.000000,19979.00000,14988.000000,300.000000,50.000000,100.000000


**Total Order Cycle Time: Total number of days taken for a customer to receive an order**

In [9]:
df['Total_order_cycle_time'] = df['Order_Processing_Time'] + df['Shipping_Time_Days']

**Total Logistics Cost: Total cost of all logistics operations combined**

In [10]:
df['Total_Logistics_Cost'] = df['Storage_Cost'] + df['Transportation_Cost'] + df['Operational_Cost']

**5. Profit Margin (Approx): Difference between sales and cost**

In [11]:
df['Net_profit'] = df['Monthly_Sales'] - (df['Total_Logistics_Cost'])

In [12]:
df[['Monthly_Sales', 'Net_profit']].head()

   Monthly_Sales  Net_profit
0           4893     -108755
1           4453      -57981
2           5956      -81518
3           5814      -63545
4           2279      -52569

In [13]:
df['Cost_Efficiency_Ratio'] = df['Total_Logistics_Cost'] / df['Monthly_Sales']

**Capacity Utilization: Percentage of warehouse space being used**

In [14]:
df['Capacity_Utilization'] = (df['Current_Stock'] / df['Warehouse_Capacity']) * 100

**Inventory Turnover Ratio: How quickly the stock is sold and replaced**

In [15]:
df['Inventory_Turnover_Ratio'] = df['Monthly_Sales'] / df['Current_Stock']

**Will we run out of stock soon**

In [16]:
df['Stock_to_Demand_Ratio'] = df['Current_Stock'] / df['Demand_Forecast']

In [17]:
df.replace([np.inf, -np.inf], 0, inplace=True)

In [18]:
df.columns

Index(['Warehouse_ID', 'Location', 'Current_Stock', 'Demand_Forecast',
       'Lead_Time_Days', 'Shipping_Time_Days', 'Stockout_Risk',
       'Operational_Cost', 'Supplier_ID', 'Product_Category', 'Monthly_Sales',
       'Order_Processing_Time', 'Return_Rate', 'Customer_Rating',
       'Warehouse_Capacity', 'Storage_Cost', 'Transportation_Cost',
       'Backorder_Quantity', 'Damaged_Goods', 'Employee_Count',
       'Total_order_cycle_time', 'Total_Logistics_Cost', 'Net_profit',
       'Cost_Efficiency_Ratio', 'Capacity_Utilization',
       'Inventory_Turnover_Ratio', 'Stock_to_Demand_Ratio'],
      dtype='object')

In [19]:
new_cols = ['Total_order_cycle_time', 'Total_Logistics_Cost', 'Net_profit', 
            'Cost_Efficiency_Ratio', 'Capacity_Utilization', 
            'Inventory_Turnover_Ratio', 'Stock_to_Demand_Ratio']


df[new_cols].isnull().sum()

Total_order_cycle_time      0
Total_Logistics_Cost        0
Net_profit                  0
Cost_Efficiency_Ratio       0
Capacity_Utilization        0
Inventory_Turnover_Ratio    0
Stock_to_Demand_Ratio       0
dtype: int64

In [20]:
df[new_cols].describe()

,Total_order_cycle_time,Total_Logistics_Cost,Net_profit,Cost_Efficiency_Ratio,Capacity_Utilization,Inventory_Turnover_Ratio,Stock_to_Demand_Ratio
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,6.698462,84151.274000,-78815.702000,22.653077,11.097874,2.735464,1.412370
std,2.323192,21931.164833,22219.320918,17.934339,8.208686,2.609801,1.501744
min,1.568792,36523.000000,-130570.000000,4.558472,1.091282,0.204481,0.110098
25%,4.976415,65828.500000,-97483.000000,10.636300,5.266148,1.141594,0.515328
50%,6.628393,84625.000000,-78697.000000,15.811373,9.128269,1.942821,0.929102
75%,8.418528,102163.250000,-61388.750000,27.866772,14.131303,3.148789,1.626190
max,11.899859,132412.000000,-28877.000000,102.487052,44.248372,17.527574,9.832645

In [21]:
df.to_csv('Final_Supply_Chain_Analysis.csv', index=False)